### ISSUE TITLE
Login doesn't set the header correctly

### ISSUE THREAD

**Issue by nick-verida** [verida/vue-starter-kit#17]
When logging in (using `"@verida/vue-account": "^0.1.31",`) the header isn't set.

See https://www.loom.com/share/a465e06237ab429587e2a047ac2effba 

This can currently (5-May-2022) be replicated on the https://bug-cannot-use-messaging.d2h6ykwy81i9ka.amplifyapp.com/ site, although that site will go away once that branch is deleted

**Comment by cmcWebCode40** [comment]
@Nick, 

I have fixed and updated this code to use the changes I made in [commit](https://github.com/verida/verida-vue-components/commit/b612a05e2bf8c6606d462680762567a9a3867437) 

I will Open a Open a PR for the vue-component.
